# Generated by Django 4.2.3 on 2023-07-27 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_text', models.CharField(max_length=20, verbose_name='Верхний текст')),
                ('main_text', models.CharField(max_length=6, verbose_name='Главный средний текст')),
                ('bottom_text', models.CharField(max_length=20, verbose_name='Нижний текст')),
            ],
        ),
        migrations.CreateModel(
            name='NavbarLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название ссылки')),
                ('url', models.CharField(verbose_name='Сслылка')),
            ],
        ),
    ]
