version: '3'

services:
  db:
    image: postgres:15.3-alpine
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    env_file:
      - ./.env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - backend

  backend:
    build:
      context: ./back/spacexmp
      dockerfile: Dockerfile
    command: >
      sh -c " python3 ./spacexmp/manage.py migrate
              python3 ./spacexmp/manage.py runserver 0.0.0.0:8000"
    container_name: backend
    hostname: backend
    tty: true
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db
    networks:
      - backend
    volumes:
      - ./back:/var/www

  frontend:
    container_name: frontend
    build:
      context: ./front
      dockerfile: Dockerfile
    command: npm run dev
    depends_on:
      - backend
      - db
    restart: always
    volumes:
      - ./front:/var/front
    ports:
      - "5173:5173"
    networks:
      - backend

networks:
  backend:

volumes:
  postgres_data:
  pgadmin-data: